added solution
IgorBochkor/bank-service pull request #1
Opened 2021-03-01 15:39 UTC by IgorBochkor

added solution

2021-03-01 15:53 UTC, YuraBondarenko approved these changes

2021-03-01 15:53 UTC, YuraBondarenko commented on src/main/java/com/dev/boot/bankservice/service/impl/UserServiceImpl.java
> +    }
checklist
instead of methods `create `and `update`, create method `save`

2021-03-01 17:20 UTC, KseniiaMakarova requested changes

2021-03-01 17:20 UTC, KseniiaMakarova commented on src/main/java/com/dev/boot/bankservice/model/User.java
> +public class User {
add `@Table` annotation

2021-03-01 17:20 UTC, KseniiaMakarova commented on src/main/java/com/dev/boot/bankservice/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
adding `FetchType.EAGER` is bad practice

2021-03-01 17:20 UTC, KseniiaMakarova commented on src/main/java/com/dev/boot/bankservice/model/User.java
> +
remove redundant empty lines

2021-03-01 17:20 UTC, KseniiaMakarova commented on src/main/java/com/dev/boot/bankservice/repository/UserRepository.java
> +    Optional<User> findByPhoneNumber(String phoneNumber);
let's use join fetch in this method and in `findById()` as well

2021-03-01 17:20 UTC, KseniiaMakarova commented on src/main/java/com/dev/boot/bankservice/service/UserService.java
> +    User update(User user);
let's see checklist

2021-03-01 17:20 UTC, KseniiaMakarova commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:testdb
let's enable the console so that we could have access to our db from the browser

2021-03-02 09:02 UTC, KseniiaMakarova approved these changes

2021-03-02 10:56 UTC, merged